services:
  app:
    build: .
    platform: linux/amd64
    container_name: kikichy_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: kikichy_db
      DB_USERNAME: root
      DB_PASSWORD: root
    working_dir: /var/www/html
    restart: unless-stopped

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: kikichy_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kikichy_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
